# test tag -  v1.0.2
# verification - название объекта QPushButton - 'Верефикация'
# openingButton - название объекта QPushButton - 'Открыть...'
# saveButton - название объекта QPushButton - 'Сохранить'
# module_txt - название объекта QComboBox - 'Тип модуля'
# system_num_txt - название объекта QPlainTextEdit - 'Системный № модуля'
# station_num_txt - название объекта QPlainTextEdit - '№ станции'
# way_num_txt - название объекта QPlainTextEdit - '№ пути'
# rack_num_txt - название объекта QPlainTextEdit - '№ шкафа'
# crate_num_txt - название объекта QPlainTextEdit - '№ модуля'
# crate_place_txt - название объекта QPlainTextEdit - '№ места'
# rec_code1_txt - название объекта QPlainTextEdit - 'Индивидуальная информация'
# rec_code2_txt - название объекта QPlainTextEdit - 'Индивидуальная информация'
# rec_code3_txt - название объекта QPlainTextEdit - 'Индивидуальная информация'
# rec_code4_txt - название объекта QPlainTextEdit - 'Индивидуальная информация'
# crc32_txt - название объекта QLabel - 'Контрольная сумма'
# operationStatus - название объекта QLabel - 'Статус операции'
# GUIVersion - название объекта QLabel - 'GUI version 0.0'
# FIRMWAREVersion - название объекта QLabel - 'FIRMWARE version 0.0'

from PyQt6 import QtCore, QtGui, QtWidgets
import git

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 670)
        style_file = QtCore.QFile("styleForABTC-i.css")
        style_file.open(QtCore.QIODevice.OpenModeFlag.ReadOnly | QtCore.QIODevice.OpenModeFlag.Text)
        style_sheet = style_file.readAll().data().decode("utf-8")
        style_file.close()
        MainWindow.setStyleSheet(style_sheet)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        MainWindow.setFont(font)
        self.globalWrapper = QtWidgets.QWidget(parent=MainWindow)
        self.globalWrapper.setObjectName("globalWrapper")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.globalWrapper)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mianBlock = QtWidgets.QFrame(parent=self.globalWrapper)
        self.mianBlock.setObjectName("mianBlock")
        self.formLayout = QtWidgets.QFormLayout(self.mianBlock)
        self.formLayout.setObjectName("formLayout")
        self.titleFierst = QtWidgets.QLabel(parent=self.mianBlock)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.titleFierst.setFont(font)
        self.titleFierst.setObjectName("titleFierst")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.titleFierst)
        self.module = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module.sizePolicy().hasHeightForWidth())
        self.module.setSizePolicy(sizePolicy)
        self.module.setObjectName("module")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.module)
        self.module_txt = QtWidgets.QComboBox(parent=self.mianBlock)
        self.module_txt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_txt.sizePolicy().hasHeightForWidth())
        self.module_txt.setSizePolicy(sizePolicy)
        self.module_txt.setMaximumSize(QtCore.QSize(16777215, 22))
        self.module_txt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.module_txt.setMouseTracking(False)
        self.module_txt.setTabletTracking(False)
        self.module_txt.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.module_txt.setAcceptDrops(False)
        self.module_txt.setAutoFillBackground(False)
        self.module_txt.setEditable(False)
        self.module_txt.setIconSize(QtCore.QSize(16, 16))
        self.module_txt.setFrame(True)
        self.module_txt.setModelColumn(0)
        self.module_txt.setObjectName("module_txt")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.module_txt.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.module_txt)
        self.system_num = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system_num.sizePolicy().hasHeightForWidth())
        self.system_num.setSizePolicy(sizePolicy)
        self.system_num.setObjectName("system_num")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.system_num)
        self.system_num_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.system_num_txt.setEnabled(True)
        self.system_num_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.system_num_txt.setFont(font)
        self.system_num_txt.setMouseTracking(False)
        self.system_num_txt.setTabletTracking(False)
        self.system_num_txt.setAcceptDrops(True)
        self.system_num_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.system_num_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.system_num_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.system_num_txt.setObjectName("system_num_txt")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.system_num_txt)
        self.station_num = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.station_num.sizePolicy().hasHeightForWidth())
        self.station_num.setSizePolicy(sizePolicy)
        self.station_num.setObjectName("station_num")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.station_num)
        self.station_num_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.station_num_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.station_num_txt.setFont(font)
        self.station_num_txt.setMouseTracking(False)
        self.station_num_txt.setTabletTracking(False)
        self.station_num_txt.setAcceptDrops(True)
        self.station_num_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.station_num_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.station_num_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.station_num_txt.setObjectName("station_num_txt")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.station_num_txt)
        self.way_num = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.way_num.sizePolicy().hasHeightForWidth())
        self.way_num.setSizePolicy(sizePolicy)
        self.way_num.setObjectName("way_num")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.way_num)
        self.way_num_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.way_num_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.way_num_txt.setFont(font)
        self.way_num_txt.setMouseTracking(False)
        self.way_num_txt.setTabletTracking(False)
        self.way_num_txt.setAcceptDrops(True)
        self.way_num_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.way_num_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.way_num_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.way_num_txt.setObjectName("way_num_txt")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.way_num_txt)
        self.rack_num = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rack_num.sizePolicy().hasHeightForWidth())
        self.rack_num.setSizePolicy(sizePolicy)
        self.rack_num.setObjectName("rack_num")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rack_num)
        self.rack_num_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.rack_num_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.rack_num_txt.setFont(font)
        self.rack_num_txt.setMouseTracking(False)
        self.rack_num_txt.setTabletTracking(False)
        self.rack_num_txt.setAcceptDrops(True)
        self.rack_num_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rack_num_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.rack_num_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.rack_num_txt.setObjectName("rack_num_txt")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rack_num_txt)
        self.crate_num = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crate_num.sizePolicy().hasHeightForWidth())
        self.crate_num.setSizePolicy(sizePolicy)
        self.crate_num.setObjectName("crate_num")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.crate_num)
        self.crate_num_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.crate_num_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.crate_num_txt.setFont(font)
        self.crate_num_txt.setMouseTracking(False)
        self.crate_num_txt.setTabletTracking(False)
        self.crate_num_txt.setAcceptDrops(True)
        self.crate_num_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.crate_num_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.crate_num_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.crate_num_txt.setObjectName("crate_num_txt")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.crate_num_txt)
        self.crate_place = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crate_place.sizePolicy().hasHeightForWidth())
        self.crate_place.setSizePolicy(sizePolicy)
        self.crate_place.setObjectName("crate_place")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.crate_place)
        self.crate_place_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.crate_place_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.crate_place_txt.setFont(font)
        self.crate_place_txt.setMouseTracking(False)
        self.crate_place_txt.setTabletTracking(False)
        self.crate_place_txt.setAcceptDrops(True)
        self.crate_place_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.crate_place_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.crate_place_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.crate_place_txt.setObjectName("crate_place_txt")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.crate_place_txt)
        self.rec_code1 = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rec_code1.sizePolicy().hasHeightForWidth())
        self.rec_code1.setSizePolicy(sizePolicy)
        self.rec_code1.setObjectName("rec_code1")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rec_code1)
        self.rec_code1_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.rec_code1_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.rec_code1_txt.setFont(font)
        self.rec_code1_txt.setMouseTracking(False)
        self.rec_code1_txt.setTabletTracking(False)
        self.rec_code1_txt.setAcceptDrops(True)
        self.rec_code1_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rec_code1_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.rec_code1_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.rec_code1_txt.setObjectName("rec_code1_txt")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rec_code1_txt)
        self.rec_code2 = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rec_code2.sizePolicy().hasHeightForWidth())
        self.rec_code2.setSizePolicy(sizePolicy)
        self.rec_code2.setObjectName("rec_code2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rec_code2)
        self.rec_code2_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.rec_code2_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.rec_code2_txt.setFont(font)
        self.rec_code2_txt.setMouseTracking(False)
        self.rec_code2_txt.setTabletTracking(False)
        self.rec_code2_txt.setAcceptDrops(True)
        self.rec_code2_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rec_code2_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.rec_code2_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.rec_code2_txt.setObjectName("rec_code2_txt")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rec_code2_txt)
        self.rec_code3 = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rec_code3.sizePolicy().hasHeightForWidth())
        self.rec_code3.setSizePolicy(sizePolicy)
        self.rec_code3.setObjectName("rec_code3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rec_code3)
        self.rec_code3_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.rec_code3_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.rec_code3_txt.setFont(font)
        self.rec_code3_txt.setMouseTracking(False)
        self.rec_code3_txt.setTabletTracking(False)
        self.rec_code3_txt.setAcceptDrops(True)
        self.rec_code3_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rec_code3_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.rec_code3_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.rec_code3_txt.setObjectName("rec_code3_txt")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rec_code3_txt)
        self.rec_code4 = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rec_code4.sizePolicy().hasHeightForWidth())
        self.rec_code4.setSizePolicy(sizePolicy)
        self.rec_code4.setObjectName("rec_code4")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rec_code4)
        self.crc32 = QtWidgets.QLabel(parent=self.mianBlock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crc32.sizePolicy().hasHeightForWidth())
        self.crc32.setSizePolicy(sizePolicy)
        self.crc32.setObjectName("crc32")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.ItemRole.LabelRole, self.crc32)
        self.crc32_txt = QtWidgets.QLabel(parent=self.mianBlock)
        self.crc32_txt.setMinimumSize(QtCore.QSize(0, 25))
        self.crc32_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        self.crc32_txt.setMidLineWidth(0)
        self.crc32_txt.setText("")
        self.crc32_txt.setObjectName("crc32_txt")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.ItemRole.FieldRole, self.crc32_txt)
        self.rec_code4_txt = QtWidgets.QPlainTextEdit(parent=self.mianBlock)
        self.rec_code4_txt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.rec_code4_txt.setFont(font)
        self.rec_code4_txt.setMouseTracking(False)
        self.rec_code4_txt.setTabletTracking(False)
        self.rec_code4_txt.setAcceptDrops(True)
        self.rec_code4_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rec_code4_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.rec_code4_txt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.rec_code4_txt.setObjectName("rec_code4_txt")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rec_code4_txt)
        self.verticalLayout_3.addWidget(self.mianBlock)
        self.mainButtons = QtWidgets.QFrame(parent=self.globalWrapper)
        self.mainButtons.setStyleSheet("")
        self.mainButtons.setObjectName("mainButtons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.mainButtons)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttons = QtWidgets.QFrame(parent=self.mainButtons)
        self.buttons.setObjectName("buttons")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.buttons)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonsTop = QtWidgets.QFrame(parent=self.buttons)
        self.buttonsTop.setObjectName("buttonsTop")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttonsTop)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vrification = QtWidgets.QPushButton(parent=self.buttonsTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vrification.sizePolicy().hasHeightForWidth())
        self.vrification.setSizePolicy(sizePolicy)
        self.vrification.setMinimumSize(QtCore.QSize(95, 0))
        self.vrification.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.vrification.setObjectName("vrification")
        self.verticalLayout.addWidget(self.vrification)
        self.verticalLayout_2.addWidget(self.buttonsTop)
        self.buttonsBottom = QtWidgets.QFrame(parent=self.buttons)
        self.buttonsBottom.setObjectName("buttonsBottom")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttonsBottom)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.openingButton = QtWidgets.QPushButton(parent=self.buttonsBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openingButton.sizePolicy().hasHeightForWidth())
        self.openingButton.setSizePolicy(sizePolicy)
        self.openingButton.setMinimumSize(QtCore.QSize(95, 0))
        self.openingButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.openingButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.openingButton.setObjectName("openingButton")
        self.horizontalLayout_3.addWidget(self.openingButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.buttonsBottom)
        self.saveButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(95, 0))
        self.saveButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.saveButton.setMouseTracking(False)
        self.saveButton.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.saveButton.setAutoFillBackground(False)
        self.saveButton.setCheckable(False)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.verticalLayout_2.addWidget(self.buttonsBottom)
        self.horizontalLayout_4.addWidget(self.buttons)
        spacerItem = QtWidgets.QSpacerItem(520, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.mainButtons)
        spacerItem1 = QtWidgets.QSpacerItem(40, 700, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.footer = QtWidgets.QHBoxLayout()
        self.footer.setObjectName("footer")
        self.operationStatus = QtWidgets.QLabel(parent=self.globalWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operationStatus.sizePolicy().hasHeightForWidth())
        self.operationStatus.setSizePolicy(sizePolicy)
        self.operationStatus.setObjectName("operationStatus")
        self.footer.addWidget(self.operationStatus)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footer.addItem(spacerItem2)
        self.footerList = QtWidgets.QHBoxLayout()
        self.footerList.setSpacing(0)
        self.footerList.setObjectName("footerList")
        self.GUIVersion = QtWidgets.QLabel(parent=self.globalWrapper)
        self.GUIVersion.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GUIVersion.sizePolicy().hasHeightForWidth())
        self.GUIVersion.setSizePolicy(sizePolicy)
        self.GUIVersion.setObjectName("GUIVersion")
        self.footerList.addWidget(self.GUIVersion)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerList.addItem(spacerItem3)
        self.FIRMWAREVersion = QtWidgets.QLabel(parent=self.globalWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FIRMWAREVersion.sizePolicy().hasHeightForWidth())
        self.FIRMWAREVersion.setSizePolicy(sizePolicy)
        self.FIRMWAREVersion.setObjectName("FIRMWAREVersion")
        self.footerList.addWidget(self.FIRMWAREVersion)
        self.footer.addLayout(self.footerList)
        self.verticalLayout_3.addLayout(self.footer)
        MainWindow.setCentralWidget(self.globalWrapper)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.module_txt.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TestProjectPyQt"))
        self.titleFierst.setText(_translate("MainWindow", "АБТЦ-И"))
        self.module.setText(_translate("MainWindow", "Тип модуля"))
        self.module_txt.setPlaceholderText(_translate("MainWindow","Выбери тип модуля"))
        self.module_txt.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.module_txt.setItemText(0, _translate("MainWindow", "Стенд проверки\'"))
        self.module_txt.setItemText(1, _translate("MainWindow", "Модуль управления МУ"))
        self.module_txt.setItemText(2, _translate("MainWindow", "Модуль путевых приемников МПП"))
        self.module_txt.setItemText(3, _translate("MainWindow", "Модуль путевых генераторов ГКС2 питающих концов РЦ"))
        self.module_txt.setItemText(4, _translate("MainWindow", "Модуль путевых генераторов ГКС2 приемных концов РЦ"))
        self.module_txt.setItemText(5, _translate("MainWindow", "Модуль безопасного коммутатора БКС"))
        self.module_txt.setItemText(6, _translate("MainWindow", "Модуль управления охраняемым переездом МАПС-АШ"))
        self.module_txt.setItemText(7, _translate("MainWindow", "Модуль интерфейса с релейной электрической централизацией МЭЦ"))
        self.module_txt.setItemText(8, _translate("MainWindow", "Модуль управления светофором МУС-ППМ-Ц (светофоры)"))
        self.module_txt.setItemText(9, _translate("MainWindow", "Модуль управления светофором МУС-ППМ-Ц (неохраняемые переезды)"))
        self.module_txt.setItemText(10, _translate("MainWindow", "Модуль радиоканала и часов реального времени МРК и РВ"))
        self.module_txt.setItemText(11, _translate("MainWindow", "Модуль связи с соседней станцией МСС"))
        self.module_txt.setItemText(12, _translate("MainWindow", "Модуль интерфейса с СКК-И (МДЦ)"))
        self.module_txt.setItemText(13, _translate("MainWindow", "Модуль интерфейса с АРМ электромеханика МАРМ-ШН"))
        self.module_txt.setItemText(14, _translate("MainWindow", "Модуль интерфейса с АРМ дежурного по станции МАРМ-ДСП"))
        self.module_txt.setItemText(15, _translate("MainWindow", "Модуль интерфейса с МПЦ-И МДЦ или CAN-RS"))
        self.module_txt.setItemText(16, _translate("MainWindow", "Модуль интерфейса с диспетчерской централизацией МДЦ"))
        self.module_txt.setItemText(17, _translate("MainWindow", "МДЦ для подключения КИД-И (для совместимости со Stellaris, после обновления ПО можно удалить)"))
        self.module_txt.setItemText(18, _translate("MainWindow", "Модуль интерфейса с системой диспетчерского контроля МДК"))
        self.module_txt.setItemText(19, _translate("MainWindow", "МДЦ для подключения ДК"))
        self.system_num.setText(_translate("MainWindow", "Системный № модуля"))
        self.system_num_txt.setPlaceholderText(_translate("MainWindow", "№ модуля"))
        self.station_num.setText(_translate("MainWindow", "№ станции"))
        self.station_num_txt.setPlaceholderText(_translate("MainWindow", "до 65535"))
        self.way_num.setText(_translate("MainWindow", "№ пути"))
        self.way_num_txt.setPlaceholderText(_translate("MainWindow", "до 255"))
        self.rack_num.setText(_translate("MainWindow", "№ шкафа"))
        self.rack_num_txt.setPlaceholderText(_translate("MainWindow", "до 255"))
        self.crate_num.setText(_translate("MainWindow", "№ модуля"))
        self.crate_num_txt.setPlaceholderText(_translate("MainWindow", "до 255"))
        self.crate_place.setText(_translate("MainWindow", "№ места"))
        self.crate_place_txt.setPlaceholderText(_translate("MainWindow", "до 255"))
        self.rec_code1.setText(_translate("MainWindow", "Индивидуальная информация"))
        self.rec_code1_txt.setPlaceholderText(_translate("MainWindow", "до 255"))
        self.rec_code2.setText(_translate("MainWindow", "Индивидуальная информация"))
        self.rec_code2_txt.setPlaceholderText(_translate("MainWindow", "до 255"))
        self.rec_code3.setText(_translate("MainWindow", "Индивидуальная информация"))
        self.rec_code3_txt.setPlaceholderText(_translate("MainWindow", "до 255"))
        self.rec_code4.setText(_translate("MainWindow", "Индивидуальная информация"))
        self.crc32.setText(_translate("MainWindow", "Контрольная сумма"))
        self.rec_code4_txt.setPlaceholderText(_translate("MainWindow", "до 255"))
        self.vrification.setText(_translate("MainWindow", "Верефикация"))
        self.openingButton.setText(_translate("MainWindow", "Открыть..."))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
        self.operationStatus.setText(_translate("MainWindow", "Статус операции:.."))
        self.GUIVersion.setText(_translate("MainWindow", f"GUI {version('G')}"))
        self.FIRMWAREVersion.setText(_translate("MainWindow", f"FIRMWARE {version('F')}"))

def version(type):
    g = git.cmd.Git()
    blob = g.ls_remote('https://github.com/Rooplok/project', sort='-v:refname', tags=True)
    list_versions = blob.split('\n')
    list_clear_versions = []
    for version in list_versions:
        list_clear_versions.append(version.split('/')[-1])

    for version in list_clear_versions:
        if version[-1] == type:
            return(version[:-1])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
